name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Create Docker network
      run: docker network create -d overlay --attachable loe_network || true

    - name: Pull new images
      run: docker compose pull

    - name: Deploy stack
      run: docker stack deploy -c docker-compose.yml loe_stack

    - name: Prune unused images
      run: echo 'y' | docker image prune -a
