name: Dev CI/CD
on:
  push:
    branches: ['dev']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: 'Install Dependencies'
        run: npm install --legacy-peer-deps

      - name: 'Build Core-App'
        run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npx nx container core-app

      - name: 'Build Partner-App'
        run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npx nx container partner-app

      - name: Copy docker folder to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          source: ./docker/dev
          target: ~/app/docker
          strip_components: 3

      - name: SSH into EC2 instance and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          script: |
            cd ~/app/docker
            echo '${{secrets.DEV_ENV_FILE}}' > .env
            echo '${{secrets.DOCKER_ACCESS_TOKEN}}' > docker_password
            make prune
            make pull
            make down
            make up
